import { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import api, { getErrorMessage } from '../api/client.js';
import { useAuth } from '../context/AuthContext.jsx';
import Badge from '../components/Badge.jsx';
import Icon from '../components/Icons.jsx';
import { PageHeader, Button, Card, ErrorBanner, EmptyState } from '../components/ui.jsx';
import PlanReview from '../components/PlanReview.jsx';
import { timeAgo } from '../lib/format.js';

export default function Approvals() {
  const { can } = useAuth();
  const [runs, setRuns] = useState([]);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(true);

  const load = useCallback(async () => {
    setBusy(true);
    setError('');
    try {
      const { data } = await api.get('/runs?limit=100');
      const pending = (data.data.runs || []).filter((r) => r.status === 'AWAITING_APPROVAL');
      setRuns(pending);
    } catch (err) {
      setError(getErrorMessage(err, 'Could not load approvals'));
    } finally {
      setBusy(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);
  useEffect(() => { const t = setInterval(load, 15000); return () => clearInterval(t); }, [load]);

  const canApprove = can('admin', 'manager');

  return (
    <div className="space-y-6">
      <PageHeader
        title="Approvals"
        subtitle="Review AI-generated browser plans before execution. Only managers and admins can approve."
        meta={`${runs.length} pending plan${runs.length === 1 ? '' : 's'}`}
        action={<Button variant="secondary" size="sm" onClick={load}><Icon name="refresh" size={16} /> Refresh</Button>}
      />
      {error && <ErrorBanner message={error} onRetry={load} />}

      {busy && !runs.length ? (
        <div className="text-sm text-gray-500">Loading approvals…</div>
      ) : runs.length === 0 ? (
        <EmptyState icon="approve" title="No pending approvals" message="When analysts generate plans, they appear here for your review." />
      ) : (
        <div className="space-y-5">
          {runs.map((run) => (
            <Card
              key={run._id}
              title={run.task?.name || 'Task'}
              subtitle={run.task?.target ? `target: ${run.task.target}` : undefined}
              action={<Badge tone="amber" dot>Awaiting approval</Badge>}
            >
              <div className="px-5 py-4 space-y-4">
                <div className="flex flex-wrap items-center gap-2 text-sm text-gray-500">
                  <span>Generated by {run.trigger || 'manual'} · {timeAgo(run.createdAt)}</span>
                  <Link to={run.task?._id ? `/tasks/${run.task._id}` : '#'} className="text-brand-600 hover:underline text-xs">Task</Link>
                </div>
                <PlanReview
                  task={{ _id: run.task?._id, plan: run.plan || [] }}
                  pendingRun={run}
                  canApprove={canApprove}
                  onDone={load}
                />
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}